version: "3.9"

volumes:
  mysql_vol:

networks:
  mysqql_net:

services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysqql_vol:/var/lib/mysql
    networks:
      - mysqql_net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_PASSWORD=1234
      - MYSQL_USER=user
      - MYSQL_DATABASE=user_db
