version: "3.9"

volumes:
  postgres_vol:

networks:
  postgres_net:

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    networks:
      - postgres_net
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev_db
