version: "3.9"

networks:
  rabbitmq_net:

volumes:
  rabbitmq_data_vol:
  rabbitmq_log_vol:

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data_vol:/var/lib/rabbitmq/
        - rabbitmq_log_vol:/var/log/rabbitmq
    networks:
        - rabbitmq_net
    environment:
          - RABBITMQ_DEFAULT_USER = admin
          - RABBITMQ_DEFAULT_PASS = 1234