version: "3.9"

networks:
  redis_net:

services:
  redis:
    image: redis:6.2-alpine
    networks:
      - redis_net
    ports:
      - 6379:6379
    command: redis-server --save 60 1 --requirepass MDNcVb924a --loglevel warning
