version: "3.9"

networks:
  sqlserver_net:

volumes:
  sqlserver_system:
  sqlserver_data:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - sqlserver_system:/var/opt/mssql
      - sqlserver_data:/var/opt/sqlserver
    networks:
      - sqlserver_net
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
      - MSSQL_PID=Express
