version: "3.9"

networks:
  sqlserver_net:

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    networks:
      - sqlserver_net
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=mssql1Ipw
